"""Where Russian IT employers post jobs.

Live boards are in ``career_catalog.BOARDS`` and Hunt can fetch them.
Everything else is the research queue: own career site, HH-only, or no feed.
Sources: Habr Career rating 2025, Habr employer-brand 2025, HighTime 2026,
TAdviser500 2026, Innopolis PISH partners PDF.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CareerTarget:
    slug: str
    name: str
    jobs_url: str
    channel: str  # live | own | hh | none
    sources: str
    note: str = ""


# channel:
#   live — Hunt already fetches IT feed (career_catalog.BOARDS)
#   own  — company site / ATS, parser not wired yet
#   hh   — only hh.ru employer, already covered by HH source
#   none — no current vacancies / dead page
TARGETS: tuple[CareerTarget, ...] = (
    CareerTarget("aviasales", "Авиасейлс", "https://www.aviasales.ru/about/vacancies", "live", "habr-brand", "уже в Hunt"),
    CareerTarget("avito", "Авито", "https://career.avito.com/vacancies/razrabotka/", "live", "habr-brand,hightime,tadviser", "уже в Hunt"),
    CareerTarget("kaspersky", "Лаборатория Касперского", "https://careers.kaspersky.ru/vacancies", "live", "habr-brand,hightime,tadviser,habr-rating", "уже в Hunt"),
    CareerTarget("tbank", "Т-Банк", "https://www.tbank.ru/career/vacancies/it/", "live", "habr-brand,hightime,tadviser,innopolis", "уже в Hunt"),
    CareerTarget("vk", "VK", "https://team.vk.company/vacancy/", "live", "habr-brand,hightime,tadviser,innopolis", "уже в Hunt"),
    CareerTarget("yandex", "Яндекс", "https://yandex.ru/jobs/", "live", "habr-brand,hightime,tadviser,innopolis", "уже в Hunt"),
    CareerTarget("yadro", "YADRO", "https://careers.yadro.com/vacancies?direction=14", "live", "habr-brand,hightime,habr-rating", "IT-направление API"),
    CareerTarget("megafon", "МегаФон", "https://job.megafon.ru/", "live", "habr-brand,habr-rating,innopolis", "IT-специальности API"),
    CareerTarget("solar", "Солар", "https://team.rt-solar.ru/vacancies/", "live", "habr-brand,hightime", "ИБ, HTML-доска"),
    CareerTarget("selectel", "Selectel", "https://selectel.ru/careers/all/", "live", "habr-brand,hightime,tadviser", "HTML-карточки"),
    CareerTarget("x5", "X5 Tech", "https://x5.tech/vacancy", "live", "habr-brand,hightime,tadviser,innopolis", "лента /vacancy/{uuid}"),
    CareerTarget("itone", "IT_ONE", "https://www.it-one.ru/vacancies/", "live", "habr-brand", "JSON skip/take"),
    CareerTarget("cloudru", "Cloud.ru", "https://cloud.ru/career/vacancies", "live", "habr-brand,tadviser", "HTML-лента"),
    CareerTarget("croc", "КРОК", "https://careers.croc.ru/", "live", "habr-brand,hightime", "HTML IT-направления"),
    CareerTarget("jet", "Инфосистемы Джет", "https://jet.su/career/", "live", "habr-brand,tadviser", "HTML IT-лента"),
    CareerTarget("mts", "МТС", "https://job.mts.ru/", "live", "habr-brand", "API, фильтр IT-направлений"),
    CareerTarget("2gis", "2ГИС", "https://job.2gis.ru/", "live", "habr-brand", "API /api/v1/vacancies, IT-направления"),
    CareerTarget("dodo", "Dodo Engineering", "https://dodoengineering.ru/", "own", "habr-brand", "Tilda, лента не JSON"),
    CareerTarget("tochka", "Точка Банк", "https://tochka.com/hr/vacancies/", "own", "habr-brand,hightime", "403/SSL с ноутбука"),
    CareerTarget("alfa", "Альфа-Банк / Alfa Digital", "https://job.alfabank.ru/", "live", "habr-brand,habr-rating,innopolis", "JSON /api/vacancies, IT по title"),
    CareerTarget("ozon", "Ozon Tech", "https://job.ozon.ru/", "live", "habr-brand,habr-rating,innopolis", "anti-bot 403 вне РФ"),
    CareerTarget("raiffeisen", "Райффайзен Банк", "https://career.raiffeisen.ru/", "own", "habr-brand,habr-rating", "SPA"),
    CareerTarget("lamoda", "Lamoda Tech", "https://job.lamoda.ru/", "own", "habr-brand,habr-rating", "Huntflow в вёрстке"),
    CareerTarget("hh", "HeadHunter", "https://hh.ru/employer/1455", "hh", "habr-brand", "своя доска = HH"),
    CareerTarget("bureau1440", "Бюро 1440", "https://career.habr.com/companies/bureau1440", "own", "habr-brand", "проверить career site"),
    CareerTarget("vkusvill", "ВкусВилл", "https://job.vkusvill.ru/", "own", "habr-brand", "VPN-заглушка"),
    CareerTarget("positive", "Positive Technologies", "https://job.ptsecurity.com/", "own", "habr-brand,tadviser", "DNS с ноутбука не резолвится"),
    CareerTarget("cian", "Циан", "https://career.cian.ru/", "own", "habr-brand", "редирект на cian.ru"),
    CareerTarget("s7", "S7 Techlab", "https://career.habr.com/companies/s7techlab", "own", "habr-brand,innopolis", ""),
    CareerTarget("kontur", "Контур", "https://kontur.ru/career/vacancies", "live", "habr-brand,hightime,tadviser,habr-rating", "HTML-карточки + JSON-LD"),
    CareerTarget("bizone", "BI.ZONE", "https://bi.zone/career", "own", "habr-brand,tadviser", "404 по /career"),
    CareerTarget("okko", "Okko", "https://okko.tv/about/career", "own", "habr-brand", ""),
    CareerTarget("nexign", "Nexign", "https://nexign.com/ru/career", "own", "habr-brand,tadviser", "404"),
    CareerTarget("axenix", "Axenix", "https://axenix.pro/career", "own", "habr-brand,tadviser", ""),
    CareerTarget("severstal", "Северсталь", "https://severstal.com/rus/career/", "own", "habr-brand,innopolis", "404"),
    CareerTarget("t1", "Холдинг Т1 / Иннотех", "https://career.t1.ru/", "own", "habr-brand,hightime,tadviser,innopolis", "тяжёлый SPA"),
    CareerTarget("rosatom", "Росатом / РАСУ", "https://hh.ru/employer/2622575", "hh", "habr-brand,hightime,innopolis", ""),
    CareerTarget("nspk", "Мир Plat.Form / НСПК", "https://nspk.ru/career", "own", "habr-brand", "SSL"),
    CareerTarget("sibur", "СИБУР Цифровой", "https://sibur.digital/career", "own", "habr-brand,hightime,innopolis", "500"),
    CareerTarget("cft", "ЦФТ", "https://career.cft.ru/", "own", "habr-brand", "connection refused"),
    CareerTarget("sberdevices", "SberDevices", "https://rabota.sber.ru/search/", "own", "habr-brand", "часть Сбера"),
    CareerTarget("ecomtech", "ecom.tech", "https://ecom.tech/", "own", "habr-brand", "лендинг"),
    CareerTarget("smlab", "SM Lab", "https://smlab.ru/career", "own", "habr-brand,tadviser", "404"),
    CareerTarget("infotecs", "ИнфоТеКС", "https://www.infotecs.ru/career", "own", "habr-brand,tadviser", "SSL"),
    CareerTarget("nornickel", "Норникель Спутник", "https://jobs.nornickel.com/", "own", "habr-brand,innopolis", "DNS"),
    CareerTarget("lemana", "Лемана Тех", "https://lemanapro.ru/career", "own", "habr-brand,tadviser", "403"),
    CareerTarget("sber", "Сбер / СберТех", "https://rabota.sber.ru/search/", "own", "habr-brand,hightime,tadviser,innopolis", "Next без вакансий в HTML, вся HR-лента"),
    CareerTarget("alfastrah", "АльфаСтрахование", "https://www.alfastrah.ru/career/", "own", "habr-brand,habr-rating", ""),
    CareerTarget("gazprom-neft", "Газпром нефть", "https://career.habr.com/companies/gazprom-neft", "own", "habr-brand,innopolis", ""),
    CareerTarget("softline", "Softline", "https://softline.ru/career", "own", "habr-brand,tadviser,habr-rating", "404"),
    CareerTarget("greenatom", "Гринатом", "https://hh.ru/employer/665467", "hh", "habr-brand,hightime,tadviser", ""),
    CareerTarget("gazprom-auto", "Газпром Автоматизация", "https://www.gazprom-auto.ru/vacancies/", "own", "habr-brand,hightime,tadviser", "308"),
    CareerTarget("ibs", "IBS", "https://ibs.ru/career/", "live", "habr-brand", "HTML IT-фильтры"),
    CareerTarget("mts-fintech", "МТС Финтех", "https://job.mts.ru/", "own", "habr-brand", "общая доска МТС"),
    CareerTarget("domclick", "Домклик", "https://career.habr.com/companies/domclick", "own", "habr-brand", ""),
    CareerTarget("phosagro", "ФосАгро", "https://career.habr.com/companies/phosagro", "own", "habr-brand", ""),
    CareerTarget("mws", "МТС Web Services", "https://mts-digital.ru/career/join_us/", "own", "habr-brand,hightime,habr-rating", ""),
    CareerTarget("nlmk", "НЛМК ИТ", "https://habr.com/ru/companies/nlmk/profile/", "own", "habr-brand,tadviser", ""),
    CareerTarget("neoflex", "Neoflex", "https://career.neoflex.ru/", "own", "habr-brand,tadviser", "404"),
    CareerTarget("skyeng", "Skyeng", "https://job.skyeng.ru/", "own", "habr-brand", "SPA"),
    CareerTarget("icl", "ICL / ICL-КПО ВС", "https://icl-services.com/career", "own", "habr-brand,hightime,tadviser,innopolis", "про about, не лента"),
    CareerTarget("astra", "ГК Астра", "https://career.astralinux.ru/", "own", "habr-brand,tadviser", "DNS"),
    CareerTarget("haulmont", "Haulmont", "https://www.haulmont.ru/career", "own", "habr-brand", ""),
    CareerTarget("simbirsoft", "SimbirSoft", "https://www.simbirsoft.com/career", "own", "habr-brand,tadviser", "JSON-LD Corporation"),
    CareerTarget("gazprom-inform", "Газпром Информ", "https://www.gazpromvacancy.ru/vacancies/", "own", "habr-brand,hightime,tadviser", "общая лента Газпрома"),
    CareerTarget("glowbyte", "GlowByte", "https://glowbyteconsulting.com/career", "own", "habr-brand", "404"),
    CareerTarget("transneft", "Транснефть - Технологии", "https://career.habr.com/companies/transneft", "own", "habr-brand,innopolis", ""),
    CareerTarget("magnit", "Магнит Тех / ИТМ", "https://magnit.tech/", "own", "habr-brand,hightime,tadviser,innopolis", "почти пустой HTML"),
    CareerTarget("t2", "t2", "https://job.t2.ru/", "own", "habr-brand", "DNS"),
    CareerTarget("vtb", "ВТБ", "https://www.vtb.ru/o-banke/career", "own", "habr-brand", "SSL"),
    CareerTarget("sbermarketing", "СберМаркетинг", "https://career.habr.com/companies/sbermarketing", "own", "habr-brand", ""),
    CareerTarget("gpb", "Газпромбанк / GPB.Тех", "https://www.gazprombank.ru/career/", "own", "habr-brand,habr-rating,innopolis", "404"),
    CareerTarget("digitalleague", "Лига Цифровой Экономики", "https://digitalleague.ru/career", "own", "habr-brand,tadviser,habr-rating", ""),
    CareerTarget("psb", "ПСБ", "https://www.psbank.ru/career", "own", "habr-brand", ""),
    CareerTarget("rtlabs", "РТЛабс", "https://career.habr.com/companies/rtlabs", "own", "habr-brand", ""),
    CareerTarget("tensor", "Тензор", "https://tensor.ru/vacancies", "own", "habr-brand,hightime,tadviser", "Wasaby JS"),
    CareerTarget("iteco", "Ай-Теко", "https://career.habr.com/companies/iteco", "own", "habr-brand,tadviser", ""),
    CareerTarget("rosbank", "Росбанк", "https://career.habr.com/companies/rosbankinsurance", "own", "habr-brand", ""),
    CareerTarget("lanit", "Ланит", "https://job.lanit.ru/main/index.html", "own", "habr-brand,hightime,habr-rating", "почти пустой HTML"),
    CareerTarget("1c", "1С", "https://1c.ru/rus/firm1c/vacancy.jsp", "own", "habr-brand", ""),
    CareerTarget("domrf", "ДОМ.РФ", "https://дом.рф/career", "own", "habr-brand,habr-rating", "punycode URL"),
    CareerTarget("cbr", "Банк России", "https://cbr.ru/career", "own", "habr-brand", ""),
    CareerTarget("sovcom", "Совкомбанк Технологии", "https://people.sovcombank.ru/it", "own", "habr-brand,hightime,tadviser", ""),
    CareerTarget("diasoft", "Диасофт", "https://attraction.diasoft.ru/", "own", "habr-brand,hightime,tadviser", "DNS"),
    CareerTarget("beeline", "билайн", "https://job.beeline.ru/", "own", "habr-brand,hightime,tadviser", "403"),
    CareerTarget("bft", "БФТ", "https://hh.ru/employer/9188", "hh", "habr-brand,hightime", ""),
    CareerTarget("kuper", "Купер", "https://career.kuper.ru/", "own", "habr-brand", "DNS"),
    CareerTarget("samolet", "Самолет", "https://career.habr.com/companies/samoletgroup", "own", "habr-brand", ""),
    CareerTarget("wb", "Wildberries / WBTech", "https://career.wb.ru/", "live", "habr-brand,hightime,innopolis", "career.rwb.ru CRM API"),
    CareerTarget("gnivc", "ГНИВЦ", "https://career.gnivc.ru/", "own", "habr-brand,hightime,innopolis", "403"),
    CareerTarget("bars", "БАРС Груп", "https://bars.group/career", "own", "habr-brand,tadviser,innopolis", "таймаут"),
    CareerTarget("sberhealth", "СберЗдоровье", "https://vacancy.sberhealth.ru/", "own", "habr-brand,hightime", ""),
    CareerTarget("otr", "ОТР", "https://hh.ru/employer/11749", "hh", "habr-brand,hightime,tadviser", ""),
    CareerTarget("ditmoscow", "ДИТ Москвы", "https://career.habr.com/companies/ditmos-url", "own", "habr-brand", ""),
    CareerTarget("sibintek", "Сибинтек", "https://career.habr.com/companies/sibintek", "own", "habr-brand", ""),
    CareerTarget("rshb", "РСХБ.цифра", "https://rshbdigital.ru/vacancies", "own", "habr-brand,hightime,tadviser,innopolis", "Vue чанк, лента в JS"),
    CareerTarget("myoffice", "МойОфис", "https://myoffice.ru/about/career", "own", "habr-brand,innopolis", "404"),
    CareerTarget("mkb", "МКБ", "https://mkb.ru/career", "own", "habr-brand", ""),
    CareerTarget("bell", "Bell Integrator", "https://career.habr.com/companies/bellintegrator", "own", "habr-brand", ""),
    CareerTarget("auchan", "Ашан Тех", "https://habr.com/ru/companies/auchan/profile/", "own", "habr-brand", ""),
    CareerTarget("qiwi", "QIWI", "https://career.habr.com/companies/qiwi", "own", "habr-brand", ""),
    CareerTarget("skillbox", "Skillbox", "https://career.habr.com/companies/skillbox", "own", "habr-brand", ""),
    CareerTarget("ingos", "Ингосстрах", "https://habr.com/ru/companies/ingos_it/profile/", "own", "habr-brand", ""),
    CareerTarget("1cbit", "Первый БИТ", "https://career.habr.com/companies/pb", "own", "habr-brand,tadviser", ""),
    CareerTarget("aston", "Aston", "https://astondevs.com/career", "own", "habr-brand", "404"),
    CareerTarget("rtkit", "Ростелеком ИТ", "https://rtkit.ru/careers", "own", "habr-brand,hightime", "почти пустой HTML"),
    CareerTarget("rshb-bank", "Россельхозбанк", "https://career.habr.com/companies/rshb-ru", "own", "habr-brand", ""),
    CareerTarget("ttk", "Транстелеком", "https://career.habr.com/companies/transtelecom", "own", "habr-brand", ""),
    CareerTarget("rzd", "РЖД / НИИАС", "https://career.habr.com/companies/rzd", "own", "habr-brand,innopolis", ""),
    CareerTarget("rostelecom", "Ростелеком", "https://www.company.rt.ru/career/vacancy/", "own", "habr-brand,hightime,tadviser,innopolis,habr-rating", "вся HR-лента"),
    CareerTarget("detmir", "Детский мир", "https://career.habr.com/companies/detmir", "own", "habr-brand", ""),
    CareerTarget("ertelecom", "ЭР-Телеком", "https://career.habr.com/companies/ertelecom", "own", "habr-brand", ""),
    CareerTarget("cdek", "CDEK", "https://www.cdek.ru/ru/career", "own", "habr-brand", ""),
    CareerTarget("rutube", "Rutube", "https://habr.com/ru/companies/habr_rutube/profile/", "own", "habr-brand", ""),
    CareerTarget("megamarket", "МегаМаркет", "https://career.habr.com/companies/sbermegamarket", "own", "habr-brand", ""),
    CareerTarget("mvideo", "М.Видео-Эльдорадо", "https://habr.com/ru/companies/mvideo/profile/", "own", "habr-brand", ""),
    CareerTarget("ligastavok", "Лига Ставок", "https://career.habr.com/companies/ligastavok", "own", "habr-brand", ""),
    CareerTarget("rgs", "Росгосстрах", "https://habr.com/ru/companies/rgs_it/profile/", "own", "habr-brand", ""),
    CareerTarget("pochtatech", "Почтатех", "https://pochtatech.ru/career", "own", "habr-brand,tadviser", "DNS"),
    CareerTarget("voskhod", "НИИ Восход", "https://career.habr.com/companies/nii-voskhod", "own", "habr-brand", ""),
    CareerTarget("stoloto", "Столото", "https://habr.com/ru/companies/stoloto/profile/", "own", "habr-brand", ""),
    CareerTarget("pochtabank", "Почта Банк", "https://career.habr.com/companies/pochtabank", "own", "habr-brand", ""),
    CareerTarget("pochta", "Почта России", "https://career.habr.com/companies/pochta", "own", "habr-brand,innopolis", ""),
    CareerTarget("rsb", "Русский Стандарт", "https://career.habr.com/companies/rsb", "own", "habr-brand", ""),
    CareerTarget("rostec", "Ростех", "https://rostec.ru/careers/vacancy/", "own", "hightime,tadviser", "SSL, не IT-only"),
    CareerTarget("rtk-ct", "РТК цифровые технологии", "https://rtk-it.ru/career.php", "own", "hightime", ""),
    CareerTarget("beeline-it", "Вымпелком-ИТ", "https://job.beeline.ru/job-specialists/moskva/it-i-tekhnicheskie-funktsii/", "own", "hightime,tadviser", "403"),
    CareerTarget("ocs", "OCS Distribution", "https://hr.ocs.ru/jobs/", "own", "hightime,tadviser", "404"),
    CareerTarget("isource", "Isource", "https://hh.ru/employer/5858718", "hh", "hightime", ""),
    CareerTarget("3logic", "3Logic Group", "https://rabota.3l.ru/", "own", "hightime,tadviser", "HTML"),
    CareerTarget("mts-ai", "МВС ИИ", "https://mts.ai/career/", "own", "hightime", ""),
    CareerTarget("mont", "MONT", "https://www.mont.ru/ru-ru/vakansii", "own", "hightime,tadviser", ""),
    CareerTarget("gaz-is", "Газинформсервис", "https://www.gaz-is.ru/o-kompanii/kariera", "own", "hightime,tadviser", ""),
    CareerTarget("fil-it", "Философия.ИТ", "https://msk.meec.com.ru/Rabota-v-kompanii/?kompaniya=267225", "own", "hightime", ""),
    CareerTarget("lukoil-tech", "Лукойл-Технологии", "https://hh.ru/employer/907345", "hh", "hightime,tadviser", ""),
    CareerTarget("sber-service", "СберСервис", "https://sberbank-service.ru/vacancies/", "own", "hightime,tadviser", ""),
    CareerTarget("sber-korus", "СберКорус", "https://hh.ru/employer/946607", "hh", "hightime", ""),
    CareerTarget("dasreda", "Деловая среда", "https://dasreda.ru/career/", "own", "hightime", ""),
    CareerTarget("sber-solutions", "Сбер Решения", "https://sber-solutions.ru/career/", "own", "hightime", ""),
    CareerTarget("redsoft", "Ред Софт", "https://hh.ru/employer/221768", "hh", "hightime,tadviser", ""),
    CareerTarget("syssoft", "Сиссофт", "https://hh.ru/employer/724229", "hh", "hightime,tadviser", ""),
    CareerTarget("rtits", "РТИТС", "https://hh.ru/employer/1691965", "hh", "hightime", ""),
    CareerTarget("rosseti-digital", "Россети Цифра", "https://hh.ru/employer/816969", "hh", "hightime,tadviser", ""),
    CareerTarget("tel-int", "Телеком Интеграция", "https://tel-int.ru/work", "own", "hightime", ""),
    CareerTarget("nvbs", "НВБС", "https://vacancy.nvbs.ru/ip", "own", "hightime,tadviser", ""),
    CareerTarget("tek-inform", "ТЭК Информ", "https://www.tek-inform.ru/company/vacancy/", "own", "hightime,tadviser", ""),
    CareerTarget("rrc", "RRC Group", "https://hh.ru/employer/64", "hh", "hightime", ""),
    CareerTarget("sitronics", "Sitronics Group", "https://www.sitronics.com/career", "own", "hightime", ""),
    CareerTarget("consyst", "Консист-ОС", "https://hh.ru/employer/582248", "hh", "hightime,tadviser,innopolis", ""),
    CareerTarget("rockitsoft", "RockITsoft", "", "none", "hightime,tadviser", "нет актуальных вакансий"),
    CareerTarget("jsa", "JSA Group", "https://hh.ru/employer/2851802", "hh", "hightime,tadviser", ""),
    CareerTarget("bia", "BIA Technologies", "https://bia-tech.ru/jobs/", "own", "hightime", "401"),
    CareerTarget("terralink", "Терралинк", "https://terralink.ru/career/vacancies/", "own", "hightime", "JSON-LD Organization"),
    CareerTarget("tccenter", "ТК «Центр»", "https://hh.ru/employer/3565331", "hh", "hightime", ""),
    CareerTarget("rubytech", "Rubytech", "https://rubytech.ru/career", "own", "tadviser", ""),
    CareerTarget("iks", "ИКС Холдинг", "https://ics-holding.ru/career", "own", "tadviser", ""),
    CareerTarget("element", "Элемент", "https://hh.ru/employer", "hh", "tadviser", ""),
    CareerTarget("inventa", "Инвента", "https://inventa.ru/career", "own", "tadviser", ""),
    CareerTarget("k2tech", "К2Тех", "https://k2.tech/career", "own", "tadviser", ""),
    CareerTarget("evotor", "Эвотор", "https://evotor.ru/career", "own", "tadviser", ""),
    CareerTarget("atomdata", "Атомдата", "https://atomdata.ru/career", "own", "tadviser,innopolis", ""),
    CareerTarget("innostage", "Innostage", "https://innostage-group.ru/career", "own", "tadviser", ""),
    CareerTarget("angara", "Ангара Секьюрити", "https://angarasec.ru/career", "own", "tadviser", ""),
    CareerTarget("securitycode", "Код Безопасности", "https://www.securitycode.ru/career/", "own", "tadviser", ""),
    CareerTarget("usergate", "UserGate", "https://www.usergate.com/ru/career", "own", "tadviser,innopolis", ""),
    CareerTarget("postgrespro", "Postgres Professional", "https://postgrespro.ru/career", "own", "tadviser", ""),
    CareerTarget("reksoft", "Рексофт", "https://www.reksoft.ru/career", "own", "tadviser", ""),
    CareerTarget("korus", "КОРУС Консалтинг", "https://korusconsulting.ru/career", "own", "tadviser", ""),
    CareerTarget("arenadata", "Arenadata", "https://arenadata.tech/career", "own", "tadviser", ""),
    CareerTarget("cyberprotect", "Киберпротект", "https://cyberprotect.ru/career", "own", "tadviser,innopolis", ""),
    CareerTarget("searchinform", "SearchInform", "https://searchinform.ru/career", "own", "tadviser", ""),
    CareerTarget("ascon", "Аскон", "https://ascon.ru/career", "own", "tadviser", ""),
    CareerTarget("iiko", "iiko", "https://iiko.ru/career", "own", "tadviser", ""),
    CareerTarget("akbars-dt", "Ак Барс Цифровые Технологии", "https://akbars.digital/career", "own", "innopolis", ""),
    CareerTarget("aurora", "Открытая мобильная платформа", "https://www.omprussia.ru/career", "own", "innopolis", ""),
    CareerTarget("aquarius", "Аквариус", "https://www.aq.ru/career", "own", "innopolis", ""),
    CareerTarget("mts-lab", "МТС Лаб", "https://job.mts.ru/", "own", "innopolis", "общая доска МТС"),
    CareerTarget("tatneft", "Татнефть / процессинг", "https://www.tatneft.ru/career", "own", "tadviser,innopolis", "не IT-only"),
    CareerTarget("kamaz", "КАМАЗ", "https://kamaz.ru/career", "own", "innopolis", "не IT-only"),
    CareerTarget("yandex-funtech", "Яндекс Фантех", "https://yandex.ru/jobs", "own", "hightime", "та же доска Яндекса"),
    CareerTarget("rt-digital", "РТ Цифровые Решения", "", "none", "hightime", "нет актуальных вакансий"),
    CareerTarget("sberpodbor", "СберПодбор", "", "none", "hightime", "нет актуальных вакансий"),
)


def targets_by_channel() -> dict[str, int]:
    counts: dict[str, int] = {}
    for item in TARGETS:
        counts[item.channel] = counts.get(item.channel, 0) + 1
    return counts
